<strong>{{ message }}</strong>
<p>
    You can also try to access this page with custom parameter, such as:
    <ul>
        <li><a href="{{ BASE_URL }}example/advance/index/Haruna"><code>{{ BASE_URL }}example/advance/index/Haruna</code></a> or</li>
        <li><a href="{{ BASE_URL }}example/advance/index/Mami"><code>{{ BASE_URL }}example/advance/index/Mami</code></a> or</li> 
        <li><a href="{{ BASE_URL }}example/advance/Tomomi"><code>{{ BASE_URL }}example/advance/Tomomi</code></a> or</li>  
        <li><a href="{{ BASE_URL }}example/advance/Rina"><code>{{ BASE_URL }}example/advance/Rina</code></a> or</li>
        <li><a href="{{ BASE_URL }}example/advance/index/your name"><code>{{ BASE_URL }}example/advance/index/your name</code></a> or</li> 
        <li><a href="{{ BASE_URL }}example/advance/your name"><code>{{ BASE_URL }}example/advance/your name</code></a></li>
    </ul>
    The parameter will be shown after "hello", and the number of visit will be increased since it is saved in <code>session</code>
</p>

<div class="note">
    This page is generated by using advance routing mechanism.<br />
    advance routing mechanism works easily with such following code in your controllers:
    <pre>
    # file: /application/<b>example</b>/controllers/<b>advance</b>.py 
    class Hello Controller(object):
        def hello(self, name=None):
            if name is None:
                name = 'Mami Sasazaki'
            message  = 'Hello '+name
            return message
    </pre>
    <p>For more information about routing, please visit <a href="https://github.com/goFrendiAsgard/kokoropy">Kokoropy github repository and tutorials</a></p>
</div>

%rebase example/base title='Hello'