<strong>{{ message }}</strong>
<p>
    You can also try to access this page with custom parameter, such as:
    <ul>
        <li><a href="{{ BASE_URL }}example/advance/index/Haruna"><code>{{ BASE_URL }}example/advance/index/Haruna</code></a> or</li>
        <li><a href="{{ BASE_URL }}example/advance/index/Mami"><code>{{ BASE_URL }}example/advance/index/Mami</code></a> or</li> 
        <li><a href="{{ BASE_URL }}example/advance/Tomomi"><code>{{ BASE_URL }}example/advance/Tomomi</code></a> or</li>  
        <li><a href="{{ BASE_URL }}example/advance/Rina"><code>{{ BASE_URL }}example/advance/Rina</code></a> or</li>
        <li><a href="{{ BASE_URL }}example/advance/index/your name"><code>{{ BASE_URL }}example/advance/index/your name</code></a> or</li> 
        <li><a href="{{ BASE_URL }}example/advance/your name"><code>{{ BASE_URL }}example/advance/your name</code></a></li>
    </ul>
    The parameter will be shown after "hello", and the number of visit will be increased since it is saved in <code>session</code>
</p>

<div class="note">
    This page is generated by using advance routing mechanism. This is good if you are a <i>hypster</i> who likes to have full control of things.<br />
    Using this approach, you are forced to declare all the routing manually, including trailing slash etc. However you gain more control in exchange.<br />
    advance routing mechanism works easily with such following code in your controllers:
    <pre>
# file: /application/example/controllers/advance.py 
class Hello Controller(object):
    def hello(self, name=None):
        if name is None:
            name = 'Mami Sasazaki'
        message  = 'Hello '+name
        return message

# make a Hello_Controller instance and define the manual routing
hello_controller = Hello_Controller()

# the routing should be defined manually like this:    
route(base_url('/example/advance/hello'))(hello_controller.hello)
route(base_url('/example/advance/hello/'))(hello_controller.hello)
route(base_url('/example/advance/hello/&lt;name&gt;'))(hello_controller.hello)
route(base_url('/example/advance/hello/&lt;name&gt;/'))(hello_controller.hello)
route('something_really_strange')(hello_controller.hello)
    </pre>
    <p>For more information about routing, please visit <a href="https://github.com/goFrendiAsgard/kokoropy">Kokoropy github repository and tutorials</a></p>
</div>

%rebase('example/views/base',title='Hello')