<strong>{{ message }}</strong><br />
This page is generated by using simple route mechanism<br />   
Simple routing mechanism works easily with such following code:
<pre>
from kokoropy import route, base_url
@route(base_url('example/simple/hello_world'))
def index():
    html_response  = 'Hello world'
    return html_response
</pre>
This mechanism is good for testing and simple "hello world" application<br />'
To see more advance routing mechanism, <a href="'+base_url('/example/recommended')+'">click here</a>'
%rebase('example/base',title='Hello')