from kokoropy import route, base_url, request

"""
Simple routing (without OOP)
This is great to make a "hello world" or other small applications
"""
@route(base_url('example/simple/hello_world'))
def index():
    if 'counter' in request.SESSION:
        request.SESSION['counter'] += 1
    else:
        request.SESSION['counter'] = 1        
    # get say_hello
    html_response  = '<b>The session said that you have visit routing demo page '+str(request.SESSION['counter'])+' times</b><br />'
    html_response += 'This page is generated by using simple route mechanism<br />'    
    html_response += 'Simple routing mechanism works easily with such following code:'
    html_response += '<hr />'
    html_response += '<code><pre>'
    html_response += 'from kokoropy import route, base_url\n'
    html_response += '@route(base_url(\'example/simple/hello_world\'))\n'
    html_response += 'def index():\n'
    html_response += '    html_response  = \'Hello world\'\n'
    html_response += '    return html_response'
    html_response += '</pre></code>'
    html_response += '<hr />'
    html_response += 'This mechanism is good for testing and simple "hello world" application<br />'
    html_response += 'To see more advance routing mechanism, <a href="'+base_url('/example/recommended')+'">click here</a>'
    return html_response